### ISSUE TITLE
regarding the non-commercial license

### ISSUE THREAD

**Issue by doogyhatts** [happylittlecat2333/Auffusion#13]
I am using FoleyCrafter, which uses a checkpoint from Auffusion.
My output is just a video with sound effects from FoleyCrafter.
FoleyCrafter has an Apache 2 license while Auffusion has a non-commercial license.

Is it ok to monetise such a video (in the future)?
I am not intending to create AI webservices.

**Comment by happylittlecat2333** [comment]
Thanks for your attention!

Yes, you can monetize your video with sound effects from FoleyCrafter. However, since it uses a checkpoint from Auffusion, which is trained on non-commercial datasets and thus has a non-commercial license, please acknowledge Auffusion and the datasets. You can do this by including a GitHub link, an arXiv link, or simply mentioning the name of Auffusion.

**Comment by doogyhatts** [comment]
Thank you for your clarification!
