### ISSUE TITLE
Pipeline doesn't work with Diffusers=0.25.1

### ISSUE THREAD

**Issue by IFICL** [happylittlecat2333/Auffusion#6]
Hi, 
Do you have a plan to let your pipeline support Diffusers==0.25.1? The current code has issues loading pre-train weights from hugging face because `adapter_list`, `tokenizer_list`, `text_encoder_list` are not in the pipeline modules. 
The error happens at https://github.com/happylittlecat2333/Auffusion/blob/main/auffusion_pipeline.py#L546.

**Comment by happylittlecat2333** [comment]
Thanks for your attention! Because my auffusion_pipeline try to explore different combination of text encoder, therefore I try to hack the default StableDiffusionPipeline and add these variables. On the other hand, I trained [another model](https://huggingface.co/auffusion/auffusion-full-no-adapter) and it can use the default StableDiffusionPipeline in [notebook](https://github.com/happylittlecat2333/Auffusion/blob/main/notebooks/text_to_audio_sd.ipynb), you can try to use this model in Diffusers==0.25.1 and it might work. 

PS: the attention-based method in [notebook](https://github.com/happylittlecat2333/Auffusion/blob/main/notebooks/word_swap.ipynb) depend on Diffusers=0.18, therefore method except attention-based might work fine in your case.

**Comment by IFICL** [comment]
Thanks for your reply. This is helpful. I wonder what the performance gap between `Auffusion-Full-no-adapter` and `Auffusion-Full`.

**Comment by happylittlecat2333** [comment]
They have similar performance since I trained them with same datasets.
